---
# CSIDriver для ru.yandex.s3.csi (Источник: https://github.com/yandex-cloud/k8s-csi-s3 deploy/kubernetes/driver.yaml)
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: ru.yandex.s3.csi
spec:
  attachRequired: false
  podInfoOnMount: true
