{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "homework-chart.namespace" . }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "homework-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
{{- end }}
