apiVersion: v1
kind: Config
clusters:
- cluster:
    # Получить CA сертификат: kubectl get secret cd-token -n homework -o jsonpath='{.data.ca\.crt}'
    certificate-authority-data: PLACEHOLDER_CA_CERT
    # Получить API endpoint: kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'
    server: PLACEHOLDER_API_SERVER
  name: PLACEHOLDER_CLUSTER_NAME
contexts:
- context:
    cluster: PLACEHOLDER_CLUSTER_NAME
    namespace: homework
    user: cd
  name: cd-context
current-context: cd-context
users:
- name: cd
  user:
    # Токен будет получен из файла token (сгенерирован командой: kubectl create token cd -n homework --duration=24h > token)
    token: PLACEHOLDER_TOKEN
